### PR TITLE
Fix install.py for macOS 10.15

### PR DESCRIPTION
**Pull request by vdka**
Catalina made has moved Mail.app from `/Applications` to `/System/Applications`

### CODE REVIEW

**Comment by JayBrown** [comment]
I've added all changes from the current pull requests manually, but I'm not getting this to install a version that's compatible with Apple Mail on macOS 11.2 (Big Sur).

Have you managed to make this work somehow?

**Comment by arachsys** [comment]
> I've added all changes from the current pull requests manually, but I'm not getting this to install a version that's compatible with Apple Mail on macOS 11.2 (Big Sur).
> 
> Have you managed to make this work somehow?

Hi, author of MailFlow here. The fix for Catalina is already in the master branch of MailFlow.  However, I've never tested MailFlow or MailWrap on Big Sur, and don't have easy access to a machine to test on, so there may well be different problems there.

Does invoking `python install.py` work, or does it produce an error? (I.e. is the error that the extension doesn't install, or that it doesn't do anything once installed?)

**Comment by JayBrown** [comment]
It installs the mailbundle just fine, and it also adds the correct UUID to the Info.plist, but as "10.16", not "11" or "11.0" or "11.2". Mail then says that it's an incompatible problem.

So we might need the python equivalent of `export SYSTEM_VERSION_COMPAT=0`

I tried fumbling around with the Info.plist, e.g. shamelessly copying all UUID xml keys from a working mailbundle into MailFlow, which at some point *almost* worked, but Mail then said that it's from an unidentified developer, and that it can't check it for malware. So I code-signed ad-hoc, but alas, same thing.

In these cases ("unidentified developer") you normally need to click "Allow anyway" in macOS Security & Privacy in System Preferences, but for some reason that didn't work. And in the end, Mail still says that it's incompatible, which can't be correct, but that's what macOS apparently says at this point.

So the mailbundle seems to be in order, but for some reason Apple Mail doesn't like it, even when it's adhoc-signed.

(Intel MacBook Pro, 2018, i9)

**Comment by arachsys** [comment]
Interesting, thanks. Is this on a Mac with SIP disabled too? I wonder if they've effectively cut off all plugins by requiring code-signing for things that get linked into Mail.app, as a side-effect of a more global change. Are there other plugins that still work on Big Sur? If we can find one, especially one that installs direct from source, maybe the changes they needed will provide a good hint.

(This increasingly aggressive and unpleasant code-signing situation is one of the reasons I basically avoid touching Mac systems as much as possible nowadays, and the reason I don't have access to a Big Sur box to test/fix on. Developing Free software for a platform that sets out to be deliberately hostile to users is pretty unrewarding.)

**Comment by JayBrown** [comment]
You can still run and install unsigned code, or code that's signed ad-hoc or with a non-Apple certificate. You just need to allow it in System Preferences, or remove the quarantine extended attribute. I'm running lots of this stuff. But the MailFlow bundle doesn't have a quarantine XA, so my assumption is that either mailbundles are treated slightly differently from "normal" apps and programs, or that there's some other thing wrong that I don't know about. (Maybe it's because the bundle contains symbolic links to external paths?)

**Comment by arachsys** [comment]
Joss Brown <notifications@github.com> wrote:

> It installs the mailbundle just fine, and it also adds the correct UUID  
> to the Info.plist, but as "10.16", not "11" or "11.0" or "11.2". Mail  
> then says that it's an incompatible problem.
>
> So we might need the python equivalent of export SYSTEM_VERSION_COMPAT=0

To get the OS version, we do this:

     version = '.'.join(platform.mac_ver()[0].split('.')[:2])

This page claims Apple have rather clumsily made this return 10.16 by  
literally setting SYSTEM_VERSION_COMPAT in the Python process's environment:

   https://managingosx.wordpress.com/2020/10/06/macsysadmin-2020-update-this-one-goes-to-11/

If so, the right fix probably would be to unset SYSTEM_VERSION_COMPAT in  
the environment exactly as you say, or set it to zero if an empty value  
turns out to be equivalent to 1.

Cheers,

Chris.

**Comment by arachsys** [comment]
Joss Brown <notifications@github.com> wrote:

> (Maybe it's because the bundle contains symbolic links to external paths?)

That's another interesting possibility. That's something that Apple's own  
py2app does for, but they careless broke py2app before in a way we had to  
work around, so that doesn't mean that isn't the problem.

I think it's the 'semi_standalone' entry in the py2app options which causes  
this. It might be worth turning that off to see if it helps?

Cheers,

Chris.

**Comment by JayBrown** [comment]
So I tried setting semi_standalone to False, but it's basically the same problem. The bundle is now bigger, of course, more nested code, python obviously, still though with the 10.16 compatibility key instead of 11.0 etc. I changed that, added keys for several other Mail versions… no use… "incompatible"… then I resigned, which has to be with the `--deep` argument, and then it's the old problem: "not from a known developer".

Could it be that Mail plugins now need to be properly signed & notarized? I've never heard anything in this regard.

**Comment by JayBrown** [comment]
@vdka – did you have any luck with MailFlow on Big Sur?

**Comment by JayBrown** [comment]
It seems that a proper mailbundle installation on Big Sur needs to be performed by Finder, namely it needs to copy `~/Library/Mail/Bundles/foo.mailbundle` to `~/Library/Application Support/Mail/Plug-ins/Bundles/Users/$LOGNAME/Library/Mail/Bundles/foo.mailbundle`

A raw installation script would be somthing like this:

```
#!/bin/zsh

if [[ $1 == "--user" ]] ; then
	userinstall=true
	shift
elif [[ $1 == "--global" ]] ; then
	userinstall=false
	shift
else
	userinstall=false
fi

sourcefile="$1"
! [[ $sourcefile ]] && exit 1
! [[ -d "$sourcefile" ]] && exit 1

if $userinstall ; then
	[[ $sourcefile != "$HOME/Library/Mail/Bundles/"* ]] && exit 1
	supportdir="$HOME/Library/Application Support/Mail/Plug-ins/Bundles/Users/$LOGNAME/Library/Mail/Bundles"
	! [[ -d "$supportdir" ]] && mkdir -p "$supportdir"
else
	[[ $sourcefile != "/Library/Mail/Bundles/"* ]] && exit 1
	supportdir="$HOME/Library/Application Support/Mail/Plug-ins/Bundles/Library/Mail/Bundles"
	! [[ -d "$supportdir" ]] && mkdir -p "$supportdir"
fi

osascript << EOM
set theSourceFile to POSIX file "$sourcefile"
set theDestinationDir to POSIX file "$supportdir"
tell application "Finder"
	activate
	duplicate theSourceFile to theDestinationDir with replacing
end tell
EOM
```

But that hasn't helped either… Apple Mail just will not accept the mailflow bundle.

**Comment by arachsys** [comment]
Joss Brown ***@***.***> wrote:

> It seems that a proper mailbundle installation on Big Sur needs to be  
> performed by Finder, namely it needs to copy  
> ~/Library/Mail/Bundles/foo.mailbundle to ~/Library/Application  
> Support/Mail/Plug-ins/Bundles/Users/$LOGNAME/Library/Mail/Bundles/foo.mailbundle

Hi Joss. Wow, that sounds like a particularly crazy new hoop to jump  
through. If this is the case, I'm afraid the evidence increasingly suggests  
Big Sur is too locked-down and hostile to be able to port MailFlow and  
MailWrap, although I remain happy to offer any help or advice I can if  
anyone does want to try. Sorry! Who knows what crazy things Apple will  
break next in the name of 'security'?

Best wishes,

Chris.

**Comment by MRustad** [comment]
For what it is worth, the MacGPG plugin works on Big Sur after being updated. So there must be a way to do it. It does seem likely that signing is now required. Presumably there is a way for me to sign something for my own use (I do have xcode installed) but I'm really not familiar with the process.

**Comment by arachsys** [comment]
Hi Mark. I imagine you're right it's related to code-signing, although there may also be some other minor Mail.app changes to work around at the same time. Generally when I forwarded ported from one OS X release to another, there were slight changes in selector names or other code churn to work around, e.g. https://github.com/arachsys/mailflow/commit/2f4341a9daebe4fcf898b2320a4b9aae6e48bb6f or https://github.com/arachsys/mailflow/commit/ac1f2d397ac1938736b886b391922e1bb2694109 .

**Comment by arachsys** [comment]
If anyone is still following this, I've just posted an experimental update supporting Python 3.x. This works on my macOS 10.14.6 box, but may also help with Big Sur and Monterey.

FWIW, awilfox has MailWrap running fine on Monterey and blogged about it:

  https://catfox.life/2022/03/14/using-mailwrap-on-macos-monterey/

I've added their notes on code-signing and some other likely issues to the README, although I've not been able to properly test so there may be other issues with MailFlow that don't occur on MailWrap.

**Comment by arachsys** [comment]
PS Looking at the warnings when developing the Python 3.x patch, I noticed that py2app was stripping the libraries and binaries it was bundling into the app, which will break any existing signatures on them.

I do wonder slightly if it might work even without explicit code-signing now I've disabled that, as the error messages suggested that signatures on the Python binaries might otherwise have been carried over intact into the bundle.

**Comment by arachsys** [comment]
Hi. I believe both MailFlow and MailWrap now work correctly on the latest 12.2 and 12.3 releases of mac OS with both python2 and python3 - finally! I've had a couple of success reports, and will try to further improve the documentation to clarify any potential pitfalls as they come up.

**Comment by JayBrown** [comment]
I can confirm that it works fine on the latest macOS (12.3.1).

By the way, I've added the following for some additional re-formatting, labeled by `#ADD` and `#CHANGE`. (Note: I'm anything but a good python coder, so there are probably easier ways to do it.) This includes adding two newlines at the top, because that's where I usually put my text when I answer emails. (By the way: is there a way to tell Mail to set the cursor at the top?)

```
from AppKit import NSAlternateKeyMask, NSApplication, NSBundle, NSLog, NSMenuItem, NSUserDefaults
import objc
import re
from datetime import datetime # ADD

# ...

            if self._fixAttribution:
                attribution = view.selectedDOMRange().stringValue()
                
                attribution_text = attribution.split(u',', 2)[-1].lstrip() # CHANGE
                
                attribution_text = attribution_text.replace(" wrote:", "") # ADD
                attribution_text = attribution_text.rstrip('\r\n') # ADD
                attribution_time = attribution.split(u',', 2)[-2].lstrip() # ADD
                attribution_time = attribution_time.replace("at ", "") # ADD
                attribution_date = attribution.split(u',', 2)[-3].lstrip() # ADD
                attribution_date = attribution_date.replace("On ", "") # ADD
                attribution_date = datetime.strptime(attribution_date, '%d %b %Y') # ADD
                # NOTE: the date format here obviously depends on your macOS date format system settings
                attribution_date = datetime.strftime(attribution_date, '%Y-%m-%d') # ADD
                attribution = "\n\n"+attribution_text+" ("+attribution_date+" "+attribution_time+"):\n" # ADD
                
                if view.isAutomaticTextReplacementEnabled():
                    view.setAutomaticTextReplacementEnabled_(False)
                    view.insertText_(attribution)
                    view.setAutomaticTextReplacementEnabled_(True)
                else:
                    view.insertText_(attribution)
```

**Comment by arachsys** [comment]
Joss Brown ***@***.***> wrote:

> I can confirm that it works fine on the latest macOS (12.3.1).

Thanks!

> By the way, I've added the following for some additional re-formatting,  
> labeled by #ADD and #CHANGE. (Note: I'm anything but a good python  
> coder, so there are probably easier ways to do it.)

I'd like to do something more configurable for generating the attribution  
string, in a way that localises better too. But it wasn't obvious to me  
how to get the 'Real Name ***@***.***>' passed to us from Mail so we  
could replace it completely, and trying to reverse engineer Mail was  
painful enough as it was, hence the very hacky trimming I do at the  
moment. :)

> This includes adding two newlines at the top, because that's where I  
> usually put my text when I answer emails.

This code at line 71 of MailFlow.py removes newlines at the top and bottom  
of the message, and any newlines at the end of quoted blocks. You might be  
able to just comment it out to get the standard top-posting behaviour?  
(Possibly just comment the first line if you'd still like to trim leading  
and trailing blank lines in quoted blocks, but not remove the blank lines  
at the top of the new message?)

       view.contentElement().removeStrayLinefeeds()
       blockquotes = document.getElementsByTagName_('BLOCKQUOTE')
       for index in range(blockquotes.length()):
           if blockquotes.item_(index):
               blockquotes.item_(index).removeStrayLinefeeds()

> (By the way: is there a way to tell Mail to set the cursor at the top?)

In the swizzle of the show selector of ComposeViewController at line 120  
of MailFlow.py, you'll see that we do the cursor positioning: if there's a  
signature, we move the cursor just above it; otherwise we move to the end  
of the document.

I don't remember what Mail's default behaviour is here. It might be  
sufficient just to comment out that entire swizzle if the default  
behaviour is to top-post. Alternatively, maybe just replace the whole show  
definition with

     def show(self, old):
         result = old(self)
         self.composeWebView().moveToBeginningOfDocument_(None)
         return result

which unconditionally puts the cursor at the top of the compose window for  
every message type.

Best wishes,

Chris.

**Comment by JayBrown** [comment]
Heads up regarding **macOS 14 (Sonoma)**: According to SmallCubed, the developers of MailSuite, Apple has now, as they announced in 2021 they would eventually do, killed off Apple Mail plugins. The new (officially supported?) way forward will be Apple Mail extensions. I assume that this means that (as with Safari) these extension needs to be bundled in a properly code-signed & notarized app, or in an app from the Mac App Store. (Not sure if processes with an ad-hoc signature will be allowed to attach to Apple Mail.) It probably also means a complete rewrite, and I'm not sure if a standalone python script will cut it from now on.

**Comment by arachsys** [comment]
Hi Jay. At the moment, mailflow and mailwrap are compatible with Mail.app on macOS 12.x, but still don't work on 13.x.

There were some major major changes to the message editor in Mail.app 16.x which force non-trivial and non-obvious fixes to the way MailFlow hooks into the composer. In particular, it is no longer clear how to access the message DOM tree, which MailFlow relies on to correct attribution lines, detect plain text mode and extend indentation. Ironically, the format=flowed transformation of outbound messages still works fine if you comment out everything else.

From what you write about, it sounds like 13.x would be the end of the road for these kinds of extension even if they were successfully ported to it. The platform has become painfully locked-down and user-hostile, and Apple's MailKit doesn't allow anything like the kind of access needed to monkey patch the outbound plaintext MIME encoding: it's a much more rigid and constrained interface.

**Pull request closed without merging**
